/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Pier brand tokens
        ink: '#0B0E10',
        parchment: '#F6F4EF',
        midnight: '#121B2B',
        ledger: '#1E2F24',
        gilt: '#B8925A',
        slate: '#6B6F76',
        danger: '#7A2A2A',
        // Theme-aware colors using CSS variables
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        'input-background': 'var(--input-background)',
        ring: 'var(--ring)',
        // Legacy color names for backward compatibility
        surface: 'var(--card)',
        'surface-elevated': 'var(--secondary)',
        'border-subtle': 'var(--muted)',
        'border-strong': 'var(--border-strong)',
        'text-primary': 'var(--foreground)',
        'text-secondary': 'var(--muted-foreground)',
        'text-tertiary': 'var(--muted-foreground)',
        'accent-muted': 'rgba(184, 146, 90, 0.55)',
        'accent-text': 'var(--accent-text, var(--color-accent))',
        // Legacy support (keeping for backward compatibility)
        primary: {
          50: '#f5f5f5',
          100: '#e6e6e6',
          200: '#cccccc',
          300: '#b3b3b3',
          400: '#999999',
          500: '#808080',
          600: '#666666',
          700: '#4d4d4d',
          800: '#333333',
          900: '#1a1a1a',
          950: '#0d0d0d',
        },
      },
      fontFamily: {
        sans: ['var(--font-body)', 'AF Another Sans', 'Inter', 'system-ui', 'sans-serif'],
        body: ['var(--font-body)', 'AF Another Sans', 'Inter', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'TT Neoris', 'Georgia', 'serif'],
        mono: ['var(--font-mono)', 'Departure Mono', 'Menlo', 'monospace'],
      },
      fontWeight: {
        light: '300',
        normal: '400',
      },
      borderRadius: {
        pier: '4px',
        'pier-md': '8px',
        'pier-lg': '12px',
      },
      boxShadow: {
        hairline: 'inset 0 0 0 1px var(--border)',
        subtle: '0 1px 2px 0 rgb(11 14 16 / 0.08)',
        card: '0 1px 0 rgb(11 14 16 / 0.04), 0 1px 2px rgb(11 14 16 / 0.04)',
        raised: '0 8px 24px rgb(11 14 16 / 0.08)',
        modal: '0 24px 64px rgb(11 14 16 / 0.18)',
        lg: '0 8px 24px rgb(11 14 16 / 0.08)',
        xl: '0 24px 64px rgb(11 14 16 / 0.18)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
      },
    },
  },
  plugins: [],
};