// Supabase database types
// This is a placeholder - in production, generate types using:
// npx supabase gen types typescript --project-id <your-project-id> > src/types/supabase.ts

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name?: string;
          first_name?: string;
          last_name?: string;
          phone_number?: string;
          time_zone?: string;
          travel_preferences?: Record<string, any>;
          onboarding_completed?: boolean;
          created_at: string;
          updated_at?: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string;
          first_name?: string;
          last_name?: string;
          phone_number?: string;
          time_zone?: string;
          travel_preferences?: Record<string, any>;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          first_name?: string;
          last_name?: string;
          phone_number?: string;
          time_zone?: string;
          travel_preferences?: Record<string, any>;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          user_id: string;
          title?: string;
          description?: string;
          task_type?: string;
          assigned_agent?: string;
          status?: string;
          priority?: number;
          input_data?: Record<string, any>;
          output_data?: Record<string, any>;
          requires_human?: boolean;
          escalation_reason?: string;
          due_date?: string;
          created_at?: string;
          started_at?: string;
          completed_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title?: string;
          description?: string;
          task_type?: string;
          assigned_agent?: string;
          status?: string;
          priority?: number;
          input_data?: Record<string, any>;
          output_data?: Record<string, any>;
          requires_human?: boolean;
          escalation_reason?: string;
          due_date?: string;
          created_at?: string;
          started_at?: string;
          completed_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string;
          task_type?: string;
          assigned_agent?: string;
          status?: string;
          priority?: number;
          input_data?: Record<string, any>;
          output_data?: Record<string, any>;
          requires_human?: boolean;
          escalation_reason?: string;
          due_date?: string;
          created_at?: string;
          started_at?: string;
          completed_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          user_id: string;
          role?: string;
          content?: string;
          related_task_id?: string;
          metadata?: Record<string, any>;
          created_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          role?: string;
          content?: string;
          related_task_id?: string;
          metadata?: Record<string, any>;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          role?: string;
          content?: string;
          related_task_id?: string;
          metadata?: Record<string, any>;
          created_at?: string;
        };
      };
      integrations: {
        Row: {
          id: string;
          user_id: string;
          provider: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scopes?: string[];
          is_active?: boolean;
          last_sync_at?: string;
          sync_cursor?: string;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          provider: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scopes?: string[];
          is_active?: boolean;
          last_sync_at?: string;
          sync_cursor?: string;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          provider?: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scopes?: string[];
          is_active?: boolean;
          last_sync_at?: string;
          sync_cursor?: string;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
      };
      entities: {
        Row: {
          id: string;
          user_id: string;
          entity_type: string;
          data: Record<string, any>;
          source?: string;
          source_id?: string;
          confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          entity_type: string;
          data: Record<string, any>;
          source?: string;
          source_id?: string;
          confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          entity_type?: string;
          data?: Record<string, any>;
          source?: string;
          source_id?: string;
          confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      calendar_events: {
        Row: {
          id: string;
          user_id: string;
          gcal_event_id: string;
          gcal_calendar_id: string;
          title?: string;
          description?: string;
          location?: string;
          start_time: string;
          end_time: string;
          all_day?: boolean;
          time_zone?: string;
          status?: string;
          related_trip_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          gcal_event_id: string;
          gcal_calendar_id: string;
          title?: string;
          description?: string;
          location?: string;
          start_time: string;
          end_time: string;
          all_day?: boolean;
          time_zone?: string;
          status?: string;
          related_trip_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          gcal_event_id?: string;
          gcal_calendar_id?: string;
          title?: string;
          description?: string;
          location?: string;
          start_time?: string;
          end_time?: string;
          all_day?: boolean;
          time_zone?: string;
          status?: string;
          related_trip_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      emails: {
        Row: {
          id: string;
          user_id: string;
          gmail_message_id: string;
          gmail_thread_id?: string;
          subject?: string;
          from_address?: string;
          received_at: string;
          body_preview?: string;
          category?: string;
          extracted_data?: Record<string, any>;
          processed?: boolean;
          created_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          gmail_message_id: string;
          gmail_thread_id?: string;
          subject?: string;
          from_address?: string;
          received_at: string;
          body_preview?: string;
          category?: string;
          extracted_data?: Record<string, any>;
          processed?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          gmail_message_id?: string;
          gmail_thread_id?: string;
          subject?: string;
          from_address?: string;
          received_at?: string;
          body_preview?: string;
          category?: string;
          extracted_data?: Record<string, any>;
          processed?: boolean;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          notification_type?: string;
          action_url?: string;
          action_label?: string;
          related_entity_id?: string;
          related_task_id?: string;
          read_at?: string;
          created_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message: string;
          notification_type?: string;
          action_url?: string;
          action_label?: string;
          related_entity_id?: string;
          related_task_id?: string;
          read_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          notification_type?: string;
          action_url?: string;
          action_label?: string;
          related_entity_id?: string;
          related_task_id?: string;
          read_at?: string;
          created_at?: string;
        };
      };
      // Phase 1: Proactive Intelligence tables
      // See src/types/database-generated.ts for full type definitions
      potential_trips: {
        Row: {
          id: string;
          user_id: string;
          destination: string;
          destination_city: string | null;
          destination_country: string | null;
          start_date: string;
          end_date: string;
          detection_source: 'calendar' | 'email' | 'manual';
          source_event_id: string | null;
          source_email_id: string | null;
          confidence_score: number;
          trip_type: 'business' | 'leisure' | 'mixed' | 'unknown' | null;
          metadata: Record<string, any>;
          status: 'detected' | 'confirmed' | 'booking_in_progress' | 'booked' | 'dismissed' | 'expired';
          related_trip_id: string | null;
          related_entity_id: string | null;
          created_at: string;
          updated_at: string;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          destination: string;
          destination_city?: string | null;
          destination_country?: string | null;
          start_date: string;
          end_date: string;
          detection_source: 'calendar' | 'email' | 'manual';
          source_event_id?: string | null;
          source_email_id?: string | null;
          confidence_score: number;
          trip_type?: 'business' | 'leisure' | 'mixed' | 'unknown' | null;
          metadata?: Record<string, any>;
          status?: 'detected' | 'confirmed' | 'booking_in_progress' | 'booked' | 'dismissed' | 'expired';
          related_trip_id?: string | null;
          related_entity_id?: string | null;
          created_at?: string;
          updated_at?: string;
          expires_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          destination?: string;
          destination_city?: string | null;
          destination_country?: string | null;
          start_date?: string;
          end_date?: string;
          detection_source?: 'calendar' | 'email' | 'manual';
          source_event_id?: string | null;
          source_email_id?: string | null;
          confidence_score?: number;
          trip_type?: 'business' | 'leisure' | 'mixed' | 'unknown' | null;
          metadata?: Record<string, any>;
          status?: 'detected' | 'confirmed' | 'booking_in_progress' | 'booked' | 'dismissed' | 'expired';
          related_trip_id?: string | null;
          related_entity_id?: string | null;
          created_at?: string;
          updated_at?: string;
          expires_at?: string | null;
        };
      };
      email_context: {
        Row: {
          id: string;
          user_id: string;
          email_id: string;
          gmail_message_id: string | null;
          confirmation_type: 'flight' | 'hotel' | 'car' | 'event' | 'restaurant' | 'other';
          confirmation_code: string | null;
          parsed_data: Record<string, any>;
          extraction_confidence: number | null;
          extraction_method: string;
          extraction_errors: string[] | null;
          processed: boolean;
          related_potential_trip_id: string | null;
          parsed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          email_id: string;
          gmail_message_id?: string | null;
          confirmation_type: 'flight' | 'hotel' | 'car' | 'event' | 'restaurant' | 'other';
          confirmation_code?: string | null;
          parsed_data?: Record<string, any>;
          extraction_confidence?: number | null;
          extraction_method?: string;
          extraction_errors?: string[] | null;
          processed?: boolean;
          related_potential_trip_id?: string | null;
          parsed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          email_id?: string;
          gmail_message_id?: string | null;
          confirmation_type?: 'flight' | 'hotel' | 'car' | 'event' | 'restaurant' | 'other';
          confirmation_code?: string | null;
          parsed_data?: Record<string, any>;
          extraction_confidence?: number | null;
          extraction_method?: string;
          extraction_errors?: string[] | null;
          processed?: boolean;
          related_potential_trip_id?: string | null;
          parsed_at?: string;
          created_at?: string;
        };
      };
      user_patterns: {
        Row: {
          id: string;
          user_id: string;
          pattern_type: 'airline_preference' | 'hotel_tier' | 'booking_timing' | 'seat_preference' | 'price_sensitivity' | 'destination_frequency' | 'travel_day_preference' | 'booking_window' | 'amenity_preference' | 'loyalty_usage' | 'other';
          pattern_data: Record<string, any>;
          confidence_score: number;
          observation_count: number;
          pattern_strength: 'weak' | 'moderate' | 'strong' | 'very_strong' | null;
          last_observed: string;
          first_observed: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          pattern_type: 'airline_preference' | 'hotel_tier' | 'booking_timing' | 'seat_preference' | 'price_sensitivity' | 'destination_frequency' | 'travel_day_preference' | 'booking_window' | 'amenity_preference' | 'loyalty_usage' | 'other';
          pattern_data?: Record<string, any>;
          confidence_score: number;
          observation_count?: number;
          pattern_strength?: 'weak' | 'moderate' | 'strong' | 'very_strong' | null;
          last_observed?: string;
          first_observed?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          pattern_type?: 'airline_preference' | 'hotel_tier' | 'booking_timing' | 'seat_preference' | 'price_sensitivity' | 'destination_frequency' | 'travel_day_preference' | 'booking_window' | 'amenity_preference' | 'loyalty_usage' | 'other';
          pattern_data?: Record<string, any>;
          confidence_score?: number;
          observation_count?: number;
          pattern_strength?: 'weak' | 'moderate' | 'strong' | 'very_strong' | null;
          last_observed?: string;
          first_observed?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      opportunities: {
        Row: {
          id: string;
          user_id: string;
          type: 'trip_gap' | 'price_drop' | 'preparation' | 'upgrade' | 'expiring_benefit' | 'optimization' | 'reminder' | 'other';
          title: string;
          description: string;
          confidence_score: number;
          urgency_score: number;
          impact_score: number;
          risk_score: number;
          tier: 'action_needed' | 'prepared' | 'opportunity';
          status: 'pending' | 'shown' | 'approved' | 'dismissed' | 'snoozed' | 'expired' | 'completed';
          related_potential_trip_id: string | null;
          related_task_id: string | null;
          related_entity_id: string | null;
          metadata: Record<string, any>;
          dismissed_reason: string | null;
          snoozed_until: string | null;
          approved_at: string | null;
          created_at: string;
          updated_at: string;
          expires_at: string | null;
          shown_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: 'trip_gap' | 'price_drop' | 'preparation' | 'upgrade' | 'expiring_benefit' | 'optimization' | 'reminder' | 'other';
          title: string;
          description: string;
          confidence_score: number;
          urgency_score: number;
          impact_score: number;
          risk_score: number;
          tier: 'action_needed' | 'prepared' | 'opportunity';
          status?: 'pending' | 'shown' | 'approved' | 'dismissed' | 'snoozed' | 'expired' | 'completed';
          related_potential_trip_id?: string | null;
          related_task_id?: string | null;
          related_entity_id?: string | null;
          metadata?: Record<string, any>;
          dismissed_reason?: string | null;
          snoozed_until?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
          expires_at?: string | null;
          shown_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: 'trip_gap' | 'price_drop' | 'preparation' | 'upgrade' | 'expiring_benefit' | 'optimization' | 'reminder' | 'other';
          title?: string;
          description?: string;
          confidence_score?: number;
          urgency_score?: number;
          impact_score?: number;
          risk_score?: number;
          tier?: 'action_needed' | 'prepared' | 'opportunity';
          status?: 'pending' | 'shown' | 'approved' | 'dismissed' | 'snoozed' | 'expired' | 'completed';
          related_potential_trip_id?: string | null;
          related_task_id?: string | null;
          related_entity_id?: string | null;
          metadata?: Record<string, any>;
          dismissed_reason?: string | null;
          snoozed_until?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
          expires_at?: string | null;
          shown_at?: string | null;
        };
      };
      daily_briefs: {
        Row: {
          id: string;
          user_id: string;
          brief_date: string;
          content: string;
          opportunities_count: number;
          action_needed_count: number;
          prepared_count: number;
          opportunity_ids: string[];
          generation_method: string;
          generation_time_ms: number | null;
          generated_at: string;
          read_at: string | null;
          dismissed_at: string | null;
          notification_sent: boolean;
          notification_sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          brief_date: string;
          content: string;
          opportunities_count?: number;
          action_needed_count?: number;
          prepared_count?: number;
          opportunity_ids?: string[];
          generation_method?: string;
          generation_time_ms?: number | null;
          generated_at?: string;
          read_at?: string | null;
          dismissed_at?: string | null;
          notification_sent?: boolean;
          notification_sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          brief_date?: string;
          content?: string;
          opportunities_count?: number;
          action_needed_count?: number;
          prepared_count?: number;
          opportunity_ids?: string[];
          generation_method?: string;
          generation_time_ms?: number | null;
          generated_at?: string;
          read_at?: string | null;
          dismissed_at?: string | null;
          notification_sent?: boolean;
          notification_sent_at?: string | null;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
};

