// Supabase database types
// This is a placeholder - in production, generate types using:
// npx supabase gen types typescript --project-id <your-project-id> > src/types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      capital_member_profiles: {
        Row: {
          id: string;
          member_id: string | null;
          slug: string;
          display_name: string;
          role: 'gp' | 'lp';
          firm: string;
          title: string | null;
          location: string | null;
          aum_display: string | null;
          aum_numeric: number | null;
          check_size_display: string | null;
          check_size_max: number | null;
          check_size_min: number | null;
          currency_code: string;
          focus_sectors: string[];
          bio: string | null;
          investment_thesis: string | null;
          avatar_url: string | null;
          verified: boolean;
          status: 'draft' | 'active' | 'hidden' | 'archived';
          sort_order: number;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          member_id?: string | null;
          slug: string;
          display_name: string;
          role: 'gp' | 'lp';
          firm: string;
          title?: string | null;
          location?: string | null;
          aum_display?: string | null;
          aum_numeric?: number | null;
          check_size_display?: string | null;
          check_size_max?: number | null;
          check_size_min?: number | null;
          currency_code?: string;
          focus_sectors?: string[];
          bio?: string | null;
          investment_thesis?: string | null;
          avatar_url?: string | null;
          verified?: boolean;
          status?: 'draft' | 'active' | 'hidden' | 'archived';
          sort_order?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          member_id?: string | null;
          slug?: string;
          display_name?: string;
          role?: 'gp' | 'lp';
          firm?: string;
          title?: string | null;
          location?: string | null;
          aum_display?: string | null;
          aum_numeric?: number | null;
          check_size_display?: string | null;
          check_size_max?: number | null;
          check_size_min?: number | null;
          currency_code?: string;
          focus_sectors?: string[];
          bio?: string | null;
          investment_thesis?: string | null;
          avatar_url?: string | null;
          verified?: boolean;
          status?: 'draft' | 'active' | 'hidden' | 'archived';
          sort_order?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      capital_deals: {
        Row: {
          id: string;
          slug: string;
          name: string;
          manager_name: string;
          sponsor_profile_id: string | null;
          deal_type: 'fund' | 'co-invest' | 'secondary' | 'spv';
          asset_class: string;
          status: 'pending' | 'open' | 'closing' | 'closed';
          target_size: number;
          raised_size: number;
          min_commitment: number | null;
          currency_code: string;
          close_date: string | null;
          target_irr: number | null;
          moic_target: number | null;
          vintage: number | null;
          geography: string | null;
          sectors: string[];
          description: string;
          thesis: string | null;
          return_metric_type: 'irr' | 'moic' | 'yield' | 'custom' | 'none';
          return_display: string | null;
          holding_period_years: number | null;
          liquidity_note: string | null;
          why_pier_selected: string | null;
          contacts: Json;
          sort_order: number;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          manager_name: string;
          sponsor_profile_id?: string | null;
          deal_type: 'fund' | 'co-invest' | 'secondary' | 'spv';
          asset_class: string;
          status?: 'pending' | 'open' | 'closing' | 'closed';
          target_size: number;
          raised_size?: number;
          min_commitment?: number | null;
          currency_code?: string;
          close_date?: string | null;
          target_irr?: number | null;
          moic_target?: number | null;
          vintage?: number | null;
          geography?: string | null;
          sectors?: string[];
          description: string;
          thesis?: string | null;
          contacts?: Json;
          sort_order?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          manager_name?: string;
          sponsor_profile_id?: string | null;
          deal_type?: 'fund' | 'co-invest' | 'secondary' | 'spv';
          asset_class?: string;
          status?: 'pending' | 'open' | 'closing' | 'closed';
          target_size?: number;
          raised_size?: number;
          min_commitment?: number | null;
          currency_code?: string;
          close_date?: string | null;
          target_irr?: number | null;
          moic_target?: number | null;
          vintage?: number | null;
          geography?: string | null;
          sectors?: string[];
          description?: string;
          thesis?: string | null;
          contacts?: Json;
          sort_order?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      capital_deal_documents: {
        Row: {
          id: string;
          deal_id: string;
          label: string;
          document_type: 'deck' | 'memo' | 'tearsheet' | 'legal' | 'financials' | 'other';
          display_size: string | null;
          file_size_bytes: number | null;
          storage_path: string | null;
          external_url: string | null;
          access_level: 'members' | 'approved_interest' | 'admin';
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          deal_id: string;
          label: string;
          document_type: 'deck' | 'memo' | 'tearsheet' | 'legal' | 'financials' | 'other';
          display_size?: string | null;
          file_size_bytes?: number | null;
          storage_path?: string | null;
          external_url?: string | null;
          access_level?: 'members' | 'approved_interest' | 'admin';
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          deal_id?: string;
          label?: string;
          document_type?: 'deck' | 'memo' | 'tearsheet' | 'legal' | 'financials' | 'other';
          display_size?: string | null;
          file_size_bytes?: number | null;
          storage_path?: string | null;
          external_url?: string | null;
          access_level?: 'members' | 'approved_interest' | 'admin';
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      capital_deal_interests: {
        Row: {
          id: string;
          deal_id: string;
          member_id: string;
          request_type: 'express_interest' | 'schedule_call' | 'request_documents';
          status: 'submitted' | 'under_review' | 'approved' | 'intro_scheduled' | 'declined' | 'withdrawn';
          commitment_amount: number | null;
          currency_code: string;
          message: string | null;
          admin_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          deal_id: string;
          member_id: string;
          request_type?: 'express_interest' | 'schedule_call' | 'request_documents';
          status?: 'submitted' | 'under_review' | 'approved' | 'intro_scheduled' | 'declined' | 'withdrawn';
          commitment_amount?: number | null;
          currency_code?: string;
          message?: string | null;
          admin_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          deal_id?: string;
          member_id?: string;
          request_type?: 'express_interest' | 'schedule_call' | 'request_documents';
          status?: 'submitted' | 'under_review' | 'approved' | 'intro_scheduled' | 'declined' | 'withdrawn';
          commitment_amount?: number | null;
          currency_code?: string;
          message?: string | null;
          admin_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      capital_events: {
        Row: {
          id: string;
          slug: string;
          title: string;
          event_type: 'dinner' | 'summit' | 'roundtable' | 'experience' | 'webinar';
          status: 'draft' | 'upcoming' | 'completed' | 'cancelled';
          starts_at: string;
          ends_at: string | null;
          location: string;
          city: string;
          capacity: number | null;
          registered_count: number;
          description: string;
          recap_url: string | null;
          external_registration_url: string | null;
          external_registration_label: string | null;
          host_type: 'pier' | 'partner';
          audience: string | null;
          host_name: string | null;
          location_is_public: boolean;
          featured: boolean;
          sort_order: number;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          event_type: 'dinner' | 'summit' | 'roundtable' | 'tour' | 'webinar';
          status?: 'draft' | 'upcoming' | 'completed' | 'cancelled';
          starts_at: string;
          ends_at?: string | null;
          location: string;
          city: string;
          capacity?: number | null;
          registered_count?: number;
          description: string;
          recap_url?: string | null;
          external_registration_url?: string | null;
          external_registration_label?: string | null;
          featured?: boolean;
          sort_order?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          event_type?: 'dinner' | 'summit' | 'roundtable' | 'tour' | 'webinar';
          status?: 'draft' | 'upcoming' | 'completed' | 'cancelled';
          starts_at?: string;
          ends_at?: string | null;
          location?: string;
          city?: string;
          capacity?: number | null;
          registered_count?: number;
          description?: string;
          recap_url?: string | null;
          external_registration_url?: string | null;
          external_registration_label?: string | null;
          featured?: boolean;
          sort_order?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      capital_event_rsvps: {
        Row: {
          id: string;
          event_id: string;
          member_id: string;
          status: 'requested' | 'confirmed' | 'waitlisted' | 'attended' | 'cancelled' | 'declined';
          attendee_count: number;
          message: string | null;
          admin_notes: string | null;
          responded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          member_id: string;
          status?: 'requested' | 'confirmed' | 'waitlisted' | 'attended' | 'cancelled' | 'declined';
          attendee_count?: number;
          message?: string | null;
          admin_notes?: string | null;
          responded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          member_id?: string;
          status?: 'requested' | 'confirmed' | 'waitlisted' | 'attended' | 'cancelled' | 'declined';
          attendee_count?: number;
          message?: string | null;
          admin_notes?: string | null;
          responded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      capital_partners: {
        Row: {
          id: string;
          slug: string;
          name: string;
          category: 'hotels' | 'restaurants' | 'travel' | 'lifestyle' | 'finance' | 'health';
          tagline: string | null;
          benefit: string;
          description: string;
          website_url: string | null;
          location: string | null;
          featured: boolean;
          status: 'draft' | 'active' | 'inactive' | 'archived';
          sort_order: number;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          category: 'hotels' | 'restaurants' | 'travel' | 'lifestyle' | 'finance' | 'health';
          tagline?: string | null;
          location?: string | null;
          benefit: string;
          description: string;
          website_url?: string | null;
          featured?: boolean;
          status?: 'draft' | 'active' | 'inactive' | 'archived';
          sort_order?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          category?: 'hotels' | 'restaurants' | 'travel' | 'lifestyle' | 'finance' | 'health';
          tagline?: string | null;
          benefit?: string;
          description?: string;
          website_url?: string | null;
          featured?: boolean;
          status?: 'draft' | 'active' | 'inactive' | 'archived';
          sort_order?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      capital_partner_intros: {
        Row: {
          id: string;
          partner_id: string;
          member_id: string;
          status: 'submitted' | 'in_review' | 'introduced' | 'declined' | 'cancelled';
          message: string | null;
          contact_preference: 'email' | 'phone' | 'concierge' | null;
          admin_notes: string | null;
          introduced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          partner_id: string;
          member_id: string;
          status?: 'submitted' | 'in_review' | 'introduced' | 'declined' | 'cancelled';
          message?: string | null;
          contact_preference?: 'email' | 'phone' | 'concierge' | null;
          admin_notes?: string | null;
          introduced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          partner_id?: string;
          member_id?: string;
          status?: 'submitted' | 'in_review' | 'introduced' | 'declined' | 'cancelled';
          message?: string | null;
          contact_preference?: 'email' | 'phone' | 'concierge' | null;
          admin_notes?: string | null;
          introduced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name?: string;
          first_name?: string;
          last_name?: string;
          phone_number?: string;
          time_zone?: string;
          travel_preferences?: Record<string, any>;
          onboarding_completed?: boolean;
          created_at: string;
          updated_at?: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string;
          first_name?: string;
          last_name?: string;
          phone_number?: string;
          time_zone?: string;
          travel_preferences?: Record<string, any>;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          first_name?: string;
          last_name?: string;
          phone_number?: string;
          time_zone?: string;
          travel_preferences?: Record<string, any>;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          user_id: string;
          title?: string;
          description?: string;
          task_type?: string;
          assigned_agent?: string;
          status?: string;
          priority?: number;
          input_data?: Record<string, any>;
          output_data?: Record<string, any>;
          requires_human?: boolean;
          escalation_reason?: string;
          due_date?: string;
          created_at?: string;
          started_at?: string;
          completed_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title?: string;
          description?: string;
          task_type?: string;
          assigned_agent?: string;
          status?: string;
          priority?: number;
          input_data?: Record<string, any>;
          output_data?: Record<string, any>;
          requires_human?: boolean;
          escalation_reason?: string;
          due_date?: string;
          created_at?: string;
          started_at?: string;
          completed_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string;
          task_type?: string;
          assigned_agent?: string;
          status?: string;
          priority?: number;
          input_data?: Record<string, any>;
          output_data?: Record<string, any>;
          requires_human?: boolean;
          escalation_reason?: string;
          due_date?: string;
          created_at?: string;
          started_at?: string;
          completed_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          user_id: string;
          role?: string;
          content?: string;
          related_task_id?: string;
          metadata?: Record<string, any>;
          created_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          role?: string;
          content?: string;
          related_task_id?: string;
          metadata?: Record<string, any>;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          role?: string;
          content?: string;
          related_task_id?: string;
          metadata?: Record<string, any>;
          created_at?: string;
        };
      };
      integrations: {
        Row: {
          id: string;
          user_id: string;
          provider: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scopes?: string[];
          is_active?: boolean;
          last_sync_at?: string;
          sync_cursor?: string;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          provider: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scopes?: string[];
          is_active?: boolean;
          last_sync_at?: string;
          sync_cursor?: string;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          provider?: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scopes?: string[];
          is_active?: boolean;
          last_sync_at?: string;
          sync_cursor?: string;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
      };
      entities: {
        Row: {
          id: string;
          user_id: string;
          entity_type: string;
          data: Record<string, any>;
          source?: string;
          source_id?: string;
          confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          entity_type: string;
          data: Record<string, any>;
          source?: string;
          source_id?: string;
          confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          entity_type?: string;
          data?: Record<string, any>;
          source?: string;
          source_id?: string;
          confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      calendar_events: {
        Row: {
          id: string;
          user_id: string;
          gcal_event_id: string;
          gcal_calendar_id: string;
          title?: string;
          description?: string;
          location?: string;
          start_time: string;
          end_time: string;
          all_day?: boolean;
          time_zone?: string;
          status?: string;
          related_trip_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          gcal_event_id: string;
          gcal_calendar_id: string;
          title?: string;
          description?: string;
          location?: string;
          start_time: string;
          end_time: string;
          all_day?: boolean;
          time_zone?: string;
          status?: string;
          related_trip_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          gcal_event_id?: string;
          gcal_calendar_id?: string;
          title?: string;
          description?: string;
          location?: string;
          start_time?: string;
          end_time?: string;
          all_day?: boolean;
          time_zone?: string;
          status?: string;
          related_trip_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      emails: {
        Row: {
          id: string;
          user_id: string;
          gmail_message_id: string;
          gmail_thread_id?: string;
          subject?: string;
          from_address?: string;
          received_at: string;
          body_preview?: string;
          category?: string;
          extracted_data?: Record<string, any>;
          processed?: boolean;
          created_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          gmail_message_id: string;
          gmail_thread_id?: string;
          subject?: string;
          from_address?: string;
          received_at: string;
          body_preview?: string;
          category?: string;
          extracted_data?: Record<string, any>;
          processed?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          gmail_message_id?: string;
          gmail_thread_id?: string;
          subject?: string;
          from_address?: string;
          received_at?: string;
          body_preview?: string;
          category?: string;
          extracted_data?: Record<string, any>;
          processed?: boolean;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          notification_type?: string;
          action_url?: string;
          action_label?: string;
          related_entity_id?: string;
          related_task_id?: string;
          read_at?: string;
          created_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message: string;
          notification_type?: string;
          action_url?: string;
          action_label?: string;
          related_entity_id?: string;
          related_task_id?: string;
          read_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          notification_type?: string;
          action_url?: string;
          action_label?: string;
          related_entity_id?: string;
          related_task_id?: string;
          read_at?: string;
          created_at?: string;
        };
      };
      // Phase 1: Proactive Intelligence tables
      // See src/types/database-generated.ts for full type definitions
      potential_trips: {
        Row: {
          id: string;
          user_id: string;
          destination: string;
          destination_city: string | null;
          destination_country: string | null;
          start_date: string;
          end_date: string;
          detection_source: 'calendar' | 'email' | 'manual';
          source_event_id: string | null;
          source_email_id: string | null;
          confidence_score: number;
          trip_type: 'business' | 'leisure' | 'mixed' | 'unknown' | null;
          metadata: Record<string, any>;
          status: 'detected' | 'confirmed' | 'booking_in_progress' | 'booked' | 'dismissed' | 'expired';
          related_trip_id: string | null;
          related_entity_id: string | null;
          created_at: string;
          updated_at: string;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          destination: string;
          destination_city?: string | null;
          destination_country?: string | null;
          start_date: string;
          end_date: string;
          detection_source: 'calendar' | 'email' | 'manual';
          source_event_id?: string | null;
          source_email_id?: string | null;
          confidence_score: number;
          trip_type?: 'business' | 'leisure' | 'mixed' | 'unknown' | null;
          metadata?: Record<string, any>;
          status?: 'detected' | 'confirmed' | 'booking_in_progress' | 'booked' | 'dismissed' | 'expired';
          related_trip_id?: string | null;
          related_entity_id?: string | null;
          created_at?: string;
          updated_at?: string;
          expires_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          destination?: string;
          destination_city?: string | null;
          destination_country?: string | null;
          start_date?: string;
          end_date?: string;
          detection_source?: 'calendar' | 'email' | 'manual';
          source_event_id?: string | null;
          source_email_id?: string | null;
          confidence_score?: number;
          trip_type?: 'business' | 'leisure' | 'mixed' | 'unknown' | null;
          metadata?: Record<string, any>;
          status?: 'detected' | 'confirmed' | 'booking_in_progress' | 'booked' | 'dismissed' | 'expired';
          related_trip_id?: string | null;
          related_entity_id?: string | null;
          created_at?: string;
          updated_at?: string;
          expires_at?: string | null;
        };
      };
      email_context: {
        Row: {
          id: string;
          user_id: string;
          email_id: string;
          gmail_message_id: string | null;
          confirmation_type: 'flight' | 'hotel' | 'car' | 'event' | 'restaurant' | 'other';
          confirmation_code: string | null;
          parsed_data: Record<string, any>;
          extraction_confidence: number | null;
          extraction_method: string;
          extraction_errors: string[] | null;
          processed: boolean;
          related_potential_trip_id: string | null;
          parsed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          email_id: string;
          gmail_message_id?: string | null;
          confirmation_type: 'flight' | 'hotel' | 'car' | 'event' | 'restaurant' | 'other';
          confirmation_code?: string | null;
          parsed_data?: Record<string, any>;
          extraction_confidence?: number | null;
          extraction_method?: string;
          extraction_errors?: string[] | null;
          processed?: boolean;
          related_potential_trip_id?: string | null;
          parsed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          email_id?: string;
          gmail_message_id?: string | null;
          confirmation_type?: 'flight' | 'hotel' | 'car' | 'event' | 'restaurant' | 'other';
          confirmation_code?: string | null;
          parsed_data?: Record<string, any>;
          extraction_confidence?: number | null;
          extraction_method?: string;
          extraction_errors?: string[] | null;
          processed?: boolean;
          related_potential_trip_id?: string | null;
          parsed_at?: string;
          created_at?: string;
        };
      };
      user_patterns: {
        Row: {
          id: string;
          user_id: string;
          pattern_type: 'airline_preference' | 'hotel_tier' | 'booking_timing' | 'seat_preference' | 'price_sensitivity' | 'destination_frequency' | 'travel_day_preference' | 'booking_window' | 'amenity_preference' | 'loyalty_usage' | 'other';
          pattern_data: Record<string, any>;
          confidence_score: number;
          observation_count: number;
          pattern_strength: 'weak' | 'moderate' | 'strong' | 'very_strong' | null;
          last_observed: string;
          first_observed: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          pattern_type: 'airline_preference' | 'hotel_tier' | 'booking_timing' | 'seat_preference' | 'price_sensitivity' | 'destination_frequency' | 'travel_day_preference' | 'booking_window' | 'amenity_preference' | 'loyalty_usage' | 'other';
          pattern_data?: Record<string, any>;
          confidence_score: number;
          observation_count?: number;
          pattern_strength?: 'weak' | 'moderate' | 'strong' | 'very_strong' | null;
          last_observed?: string;
          first_observed?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          pattern_type?: 'airline_preference' | 'hotel_tier' | 'booking_timing' | 'seat_preference' | 'price_sensitivity' | 'destination_frequency' | 'travel_day_preference' | 'booking_window' | 'amenity_preference' | 'loyalty_usage' | 'other';
          pattern_data?: Record<string, any>;
          confidence_score?: number;
          observation_count?: number;
          pattern_strength?: 'weak' | 'moderate' | 'strong' | 'very_strong' | null;
          last_observed?: string;
          first_observed?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      opportunities: {
        Row: {
          id: string;
          user_id: string;
          type: 'trip_gap' | 'price_drop' | 'preparation' | 'upgrade' | 'expiring_benefit' | 'optimization' | 'reminder' | 'other';
          title: string;
          description: string;
          confidence_score: number;
          urgency_score: number;
          impact_score: number;
          risk_score: number;
          tier: 'action_needed' | 'prepared' | 'opportunity';
          status: 'pending' | 'shown' | 'approved' | 'dismissed' | 'snoozed' | 'expired' | 'completed';
          related_potential_trip_id: string | null;
          related_task_id: string | null;
          related_entity_id: string | null;
          metadata: Record<string, any>;
          dismissed_reason: string | null;
          snoozed_until: string | null;
          approved_at: string | null;
          created_at: string;
          updated_at: string;
          expires_at: string | null;
          shown_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: 'trip_gap' | 'price_drop' | 'preparation' | 'upgrade' | 'expiring_benefit' | 'optimization' | 'reminder' | 'other';
          title: string;
          description: string;
          confidence_score: number;
          urgency_score: number;
          impact_score: number;
          risk_score: number;
          tier: 'action_needed' | 'prepared' | 'opportunity';
          status?: 'pending' | 'shown' | 'approved' | 'dismissed' | 'snoozed' | 'expired' | 'completed';
          related_potential_trip_id?: string | null;
          related_task_id?: string | null;
          related_entity_id?: string | null;
          metadata?: Record<string, any>;
          dismissed_reason?: string | null;
          snoozed_until?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
          expires_at?: string | null;
          shown_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: 'trip_gap' | 'price_drop' | 'preparation' | 'upgrade' | 'expiring_benefit' | 'optimization' | 'reminder' | 'other';
          title?: string;
          description?: string;
          confidence_score?: number;
          urgency_score?: number;
          impact_score?: number;
          risk_score?: number;
          tier?: 'action_needed' | 'prepared' | 'opportunity';
          status?: 'pending' | 'shown' | 'approved' | 'dismissed' | 'snoozed' | 'expired' | 'completed';
          related_potential_trip_id?: string | null;
          related_task_id?: string | null;
          related_entity_id?: string | null;
          metadata?: Record<string, any>;
          dismissed_reason?: string | null;
          snoozed_until?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
          expires_at?: string | null;
          shown_at?: string | null;
        };
      };
      daily_briefs: {
        Row: {
          id: string;
          user_id: string;
          brief_date: string;
          content: string;
          opportunities_count: number;
          action_needed_count: number;
          prepared_count: number;
          opportunity_ids: string[];
          generation_method: string;
          generation_time_ms: number | null;
          generated_at: string;
          read_at: string | null;
          dismissed_at: string | null;
          notification_sent: boolean;
          notification_sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          brief_date: string;
          content: string;
          opportunities_count?: number;
          action_needed_count?: number;
          prepared_count?: number;
          opportunity_ids?: string[];
          generation_method?: string;
          generation_time_ms?: number | null;
          generated_at?: string;
          read_at?: string | null;
          dismissed_at?: string | null;
          notification_sent?: boolean;
          notification_sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          brief_date?: string;
          content?: string;
          opportunities_count?: number;
          action_needed_count?: number;
          prepared_count?: number;
          opportunity_ids?: string[];
          generation_method?: string;
          generation_time_ms?: number | null;
          generated_at?: string;
          read_at?: string | null;
          dismissed_at?: string | null;
          notification_sent?: boolean;
          notification_sent_at?: string | null;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      update_my_capital_member_profile: {
        Args: {
          p_role?: 'gp' | 'lp';
          p_display_name: string;
          p_firm: string;
          p_title?: string | null;
          p_location?: string | null;
          p_bio?: string | null;
          p_investment_thesis?: string | null;
          p_focus_sectors?: string[] | null;
          p_aum_display?: string | null;
          p_aum_numeric?: number | null;
          p_check_size_display?: string | null;
          p_check_size_min?: number | null;
          p_check_size_max?: number | null;
          p_currency_code?: string;
        };
        Returns: {
          id: string;
          member_id: string | null;
          slug: string;
          display_name: string;
          role: 'gp' | 'lp';
          firm: string;
          title: string | null;
          location: string | null;
          aum_display: string | null;
          aum_numeric: number | null;
          check_size_display: string | null;
          check_size_max: number | null;
          check_size_min: number | null;
          currency_code: string;
          focus_sectors: string[];
          bio: string | null;
          investment_thesis: string | null;
          avatar_url: string | null;
          verified: boolean;
          status: 'draft' | 'active' | 'hidden' | 'archived';
          sort_order: number;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
      };
    };
  };
};

