#!/usr/bin/env python3
"""
Generate comprehensive hotel seed data for NYC, LA, SF, and London
Creates SQL INSERT statements for 25 hotels per city (100 total)
"""

hotels_data = {
    'NYC': [
        {'name': 'The Greenwich Hotel', 'neighborhood': 'Tribeca', 'lat': 40.7205, 'lng': -74.0087, 'address': '377 Greenwich St, New York, NY 10013', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 950, 'quality': 92, 'notes': 'Boutique luxury in Tribeca. Exceptional service, quiet, perfect for business. Shibui Spa is world-class.'},
        {'name': 'The Bowery Hotel', 'neighborhood': 'Lower East Side', 'lat': 40.7238, 'lng': -73.9910, 'address': '335 Bowery, New York, NY 10003', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 900, 'quality': 88, 'notes': 'Iconic downtown hotel with incredible restaurant and bar scene. Very scene-y, attracts fashion and creative industry.'},
        {'name': 'The Mark Hotel', 'neighborhood': 'Upper East Side', 'lat': 40.7756, 'lng': -73.9619, 'address': '25 E 77th St, New York, NY 10075', 'rate_low': 500, 'rate_mid': 750, 'rate_high': 1200, 'quality': 95, 'notes': 'Ultra-luxury on Upper East Side. Exceptional service, very quiet and discreet. Perfect for business travelers and families.'},
        {'name': 'Ace Hotel New York', 'neighborhood': 'Flatiron', 'lat': 40.7448, 'lng': -73.9880, 'address': '20 W 29th St, New York, NY 10001', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 75, 'notes': 'Hip, creative hotel in Flatiron. Great lobby for working and socializing. Very startup/creator friendly.'},
        {'name': 'The Carlyle', 'neighborhood': 'Upper East Side', 'lat': 40.7742, 'lng': -73.9634, 'address': '35 E 76th St, New York, NY 10021', 'rate_low': 600, 'rate_mid': 850, 'rate_high': 1300, 'quality': 94, 'notes': 'Iconic Upper East Side institution. Extremely discreet, old-world luxury. Bemelmans Bar is legendary.'},
        {'name': 'The Standard High Line', 'neighborhood': 'Meatpacking District', 'lat': 40.7480, 'lng': -74.0078, 'address': '848 Washington St, New York, NY 10014', 'rate_low': 300, 'rate_mid': 500, 'rate_high': 800, 'quality': 78, 'notes': 'Modern hotel on the High Line. Incredible views, rooftop bar is very scene-y. Great for younger travelers.'},
        {'name': 'The Beekman', 'neighborhood': 'Financial District', 'lat': 40.7106, 'lng': -74.0057, 'address': '123 Nassau St, New York, NY 10038', 'rate_low': 350, 'rate_mid': 550, 'rate_high': 850, 'quality': 87, 'notes': 'Stunning historic building in FiDi with incredible atrium. Tom Colicchio restaurant. Great for business travelers.'},
        {'name': 'The Whitby Hotel', 'neighborhood': 'Midtown', 'lat': 40.7624, 'lng': -73.9776, 'address': '18 W 56th St, New York, NY 10019', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 900, 'quality': 89, 'notes': 'Firmdale Hotels property with incredible design. Kit Kemp interiors are stunning. Very quiet and elegant.'},
        {'name': 'The Ludlow Hotel', 'neighborhood': 'Lower East Side', 'lat': 40.7189, 'lng': -73.9850, 'address': '180 Ludlow St, New York, NY 10002', 'rate_low': 300, 'rate_mid': 450, 'rate_high': 700, 'quality': 76, 'notes': 'Hip LES hotel with great rooftop bar. Very scene-y, attracts creative types. Good location for nightlife.'},
        {'name': 'The Mercer', 'neighborhood': 'Soho', 'lat': 40.7231, 'lng': -73.9968, 'address': '147 Mercer St, New York, NY 10012', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 950, 'quality': 90, 'notes': 'Iconic Soho boutique hotel. Perfect location for shopping and business. Very quiet and discreet.'},
        {'name': 'The NoMad Hotel', 'neighborhood': 'Flatiron', 'lat': 40.7444, 'lng': -73.9882, 'address': '1170 Broadway, New York, NY 10001', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 900, 'quality': 88, 'notes': 'Beautiful hotel with incredible restaurant. Great location in Flatiron. Can be scene-y in common areas.'},
        {'name': 'The Plaza', 'neighborhood': 'Midtown', 'lat': 40.7648, 'lng': -73.9742, 'address': '768 5th Ave, New York, NY 10019', 'rate_low': 600, 'rate_mid': 850, 'rate_high': 1300, 'quality': 93, 'notes': 'Iconic New York landmark. Ultra-luxury with exceptional service. Perfect for families and high-profile guests.'},
        {'name': 'The Ritz-Carlton New York Central Park', 'neighborhood': 'Midtown', 'lat': 40.7654, 'lng': -73.9748, 'address': '50 Central Park S, New York, NY 10019', 'rate_low': 550, 'rate_mid': 750, 'rate_high': 1200, 'quality': 92, 'notes': 'Classic luxury with Central Park views. Exceptional Ritz-Carlton service. Perfect for families and business travelers.'},
        {'name': 'The St. Regis New York', 'neighborhood': 'Midtown', 'lat': 40.7614, 'lng': -73.9738, 'address': '2 E 55th St, New York, NY 10022', 'rate_low': 600, 'rate_mid': 800, 'rate_high': 1300, 'quality': 94, 'notes': 'Ultra-luxury St. Regis with butler service. Exceptional attention to detail. Perfect for high-profile guests.'},
        {'name': 'The Four Seasons Hotel New York', 'neighborhood': 'Midtown', 'lat': 40.7618, 'lng': -73.9708, 'address': '57 E 57th St, New York, NY 10022', 'rate_low': 650, 'rate_mid': 900, 'rate_high': 1400, 'quality': 96, 'notes': 'Ultra-luxury Four Seasons with exceptional service. Perfect for families and high-profile guests. One of the best in NYC.'},
        {'name': 'The Langham New York', 'neighborhood': 'Midtown', 'lat': 40.7510, 'lng': -73.9842, 'address': '400 5th Ave, New York, NY 10018', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 1000, 'quality': 89, 'notes': 'Elegant hotel near Empire State Building. Excellent service and quiet atmosphere. Great for business travelers.'},
        {'name': 'The Edition New York', 'neighborhood': 'Midtown', 'lat': 40.7634, 'lng': -73.9726, 'address': '701 5th Ave, New York, NY 10022', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 87, 'notes': 'Ian Schrager design hotel. Very scene-y with great restaurants and bars. Perfect for younger luxury travelers.'},
        {'name': 'The Soho Grand Hotel', 'neighborhood': 'Soho', 'lat': 40.7220, 'lng': -74.0038, 'address': '310 W Broadway, New York, NY 10013', 'rate_low': 350, 'rate_mid': 500, 'rate_high': 750, 'quality': 77, 'notes': 'Hip Soho hotel with great location for shopping and nightlife. Very scene-y, attracts creative types.'},
        {'name': 'The Crosby Street Hotel', 'neighborhood': 'Soho', 'lat': 40.7226, 'lng': -73.9968, 'address': '79 Crosby St, New York, NY 10012', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 900, 'quality': 88, 'notes': 'Firmdale Hotels property with stunning Kit Kemp design. Very quiet and elegant. Perfect Soho location.'},
        {'name': 'The Dominick Hotel', 'neighborhood': 'Soho', 'lat': 40.7244, 'lng': -74.0046, 'address': '246 Spring St, New York, NY 10013', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 86, 'notes': 'Modern luxury in Soho. Great location for shopping and business. Rooms are spacious with incredible views.'},
        {'name': 'The James New York', 'neighborhood': 'Soho', 'lat': 40.7210, 'lng': -74.0042, 'address': '27 Grand St, New York, NY 10013', 'rate_low': 350, 'rate_mid': 500, 'rate_high': 750, 'quality': 76, 'notes': 'Modern Soho hotel with great rooftop. Rooms are compact but well-designed. Good for solo work trips.'},
        {'name': 'The Roxy Hotel', 'neighborhood': 'Tribeca', 'lat': 40.7230, 'lng': -74.0048, 'address': '2 6th Ave, New York, NY 10013', 'rate_low': 300, 'rate_mid': 450, 'rate_high': 700, 'quality': 74, 'notes': 'Hip Tribeca hotel with great nightlife. Very scene-y, especially on weekends. Good for younger travelers.'},
        {'name': 'The Pendry Manhattan West', 'neighborhood': 'Hudson Yards', 'lat': 40.7540, 'lng': -74.0010, 'address': '438 W 33rd St, New York, NY 10001', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 900, 'quality': 85, 'notes': 'Modern luxury in Hudson Yards. Great for business travelers. Excellent service and modern amenities.'},
        {'name': 'The Equinox Hotel', 'neighborhood': 'Hudson Yards', 'lat': 40.7525, 'lng': -74.0020, 'address': '33 Hudson Yards, New York, NY 10001', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 1000, 'quality': 84, 'notes': 'Fitness-focused luxury hotel. Incredible gym and wellness facilities. Perfect for health-conscious travelers.'},
        {'name': 'The Chatwal', 'neighborhood': 'Midtown', 'lat': 40.7580, 'lng': -73.9855, 'address': '130 W 44th St, New York, NY 10036', 'rate_low': 500, 'rate_mid': 700, 'rate_high': 1100, 'quality': 91, 'notes': 'Art Deco luxury in Theater District. Exceptional service and elegant design. Perfect for theater lovers.'},
    ],
    'LA': [
        {'name': 'The Beverly Hills Hotel', 'neighborhood': 'Beverly Hills', 'lat': 34.0900, 'lng': -118.4119, 'address': '9641 Sunset Blvd, Beverly Hills, CA 90210', 'rate_low': 600, 'rate_mid': 850, 'rate_high': 1300, 'quality': 95, 'notes': 'Iconic Beverly Hills landmark. The Pink Palace. Exceptional service, very scene-y. Perfect for high-profile guests.'},
        {'name': 'The Chateau Marmont', 'neighborhood': 'West Hollywood', 'lat': 34.0950, 'lng': -118.3730, 'address': '8221 Sunset Blvd, West Hollywood, CA 90046', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 1000, 'quality': 88, 'notes': 'Legendary Hollywood hideaway. Extremely discreet, attracts entertainment industry. Very scene-y but private.'},
        {'name': 'The Edition Los Angeles', 'neighborhood': 'West Hollywood', 'lat': 34.0908, 'lng': -118.3750, 'address': '9040 Sunset Blvd, West Hollywood, CA 90069', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 87, 'notes': 'Modern luxury in West Hollywood. Great rooftop pool and scene. Perfect for younger luxury travelers.'},
        {'name': 'The Pendry West Hollywood', 'neighborhood': 'West Hollywood', 'lat': 34.0900, 'lng': -118.3800, 'address': '8430 Sunset Blvd, West Hollywood, CA 90069', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 1000, 'quality': 86, 'notes': 'Luxury hotel with incredible pool scene. Very scene-y, attracts entertainment and fashion industry.'},
        {'name': 'The Proper Hotel Los Angeles', 'neighborhood': 'Downtown LA', 'lat': 34.0500, 'lng': -118.2500, 'address': '1100 S Broadway, Los Angeles, CA 90015', 'rate_low': 300, 'rate_mid': 450, 'rate_high': 700, 'quality': 82, 'notes': 'Hip downtown hotel with great design. Perfect for creative types and business travelers exploring DTLA.'},
        {'name': 'The Line Hotel LA', 'neighborhood': 'Koreatown', 'lat': 34.0575, 'lng': -118.3000, 'address': '3515 Wilshire Blvd, Los Angeles, CA 90010', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 78, 'notes': 'Modern hotel in Koreatown. Great for younger travelers and creatives. Good value, scene-y rooftop.'},
        {'name': 'The Ace Hotel Downtown LA', 'neighborhood': 'Downtown LA', 'lat': 34.0440, 'lng': -118.2500, 'address': '929 S Broadway, Los Angeles, CA 90015', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 76, 'notes': 'Hip downtown hotel with great lobby for working. Very startup/creator friendly. Can be loud and scene-y.'},
        {'name': 'The Maybourne Beverly Hills', 'neighborhood': 'Beverly Hills', 'lat': 34.0700, 'lng': -118.4000, 'address': '225 N Canon Dr, Beverly Hills, CA 90210', 'rate_low': 550, 'rate_mid': 750, 'rate_high': 1200, 'quality': 93, 'notes': 'Ultra-luxury in Beverly Hills. Exceptional service, very quiet and discreet. Perfect for high-profile guests.'},
        {'name': 'The Four Seasons Hotel Los Angeles', 'neighborhood': 'Beverly Hills', 'lat': 34.0730, 'lng': -118.4100, 'address': '300 S Doheny Dr, Los Angeles, CA 90048', 'rate_low': 500, 'rate_mid': 700, 'rate_high': 1100, 'quality': 92, 'notes': 'Classic Four Seasons luxury. Excellent service, perfect for families and business travelers. Very quiet.'},
        {'name': 'The Ritz-Carlton Los Angeles', 'neighborhood': 'Downtown LA', 'lat': 34.0500, 'lng': -118.2550, 'address': '900 W Olympic Blvd, Los Angeles, CA 90015', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 89, 'notes': 'Luxury in downtown LA. Great for business travelers. Excellent service and modern amenities.'},
        {'name': 'The Sunset Tower Hotel', 'neighborhood': 'West Hollywood', 'lat': 34.0900, 'lng': -118.3750, 'address': '8358 Sunset Blvd, West Hollywood, CA 90069', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 900, 'quality': 85, 'notes': 'Art Deco landmark in West Hollywood. Great restaurant scene. Perfect for entertainment industry travelers.'},
        {'name': 'The Hollywood Roosevelt', 'neighborhood': 'Hollywood', 'lat': 34.1015, 'lng': -118.3400, 'address': '7000 Hollywood Blvd, Los Angeles, CA 90028', 'rate_low': 300, 'rate_mid': 500, 'rate_high': 800, 'quality': 80, 'notes': 'Historic Hollywood hotel. Very scene-y, great pool. Perfect for younger travelers exploring Hollywood.'},
        {'name': 'The Shutters on the Beach', 'neighborhood': 'Santa Monica', 'lat': 34.0080, 'lng': -118.4900, 'address': '1 Pico Blvd, Santa Monica, CA 90405', 'rate_low': 500, 'rate_mid': 700, 'rate_high': 1100, 'quality': 90, 'notes': 'Beachfront luxury in Santa Monica. Perfect for families and romantic getaways. Excellent service.'},
        {'name': 'The Casa del Mar', 'neighborhood': 'Santa Monica', 'lat': 34.0100, 'lng': -118.4920, 'address': '1910 Ocean Way, Santa Monica, CA 90405', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 1000, 'quality': 88, 'notes': 'Elegant beachfront hotel. Great for couples and families. Very quiet and romantic.'},
        {'name': 'The Malibu Beach Inn', 'neighborhood': 'Malibu', 'lat': 34.0300, 'lng': -118.6800, 'address': '22878 Pacific Coast Hwy, Malibu, CA 90265', 'rate_low': 600, 'rate_mid': 850, 'rate_high': 1300, 'quality': 91, 'notes': 'Beachfront luxury in Malibu. Extremely private and quiet. Perfect for high-profile guests and romantic getaways.'},
        {'name': 'The Hotel Bel-Air', 'neighborhood': 'Bel Air', 'lat': 34.0800, 'lng': -118.4400, 'address': '701 Stone Canyon Rd, Los Angeles, CA 90077', 'rate_low': 700, 'rate_mid': 950, 'rate_high': 1500, 'quality': 96, 'notes': 'Ultra-luxury hideaway in Bel Air. Extremely private and discreet. Perfect for celebrities and high-profile guests.'},
        {'name': 'The Montage Beverly Hills', 'neighborhood': 'Beverly Hills', 'lat': 34.0680, 'lng': -118.4000, 'address': '225 N Canon Dr, Beverly Hills, CA 90210', 'rate_low': 600, 'rate_mid': 850, 'rate_high': 1300, 'quality': 94, 'notes': 'Ultra-luxury in Beverly Hills. Exceptional service, perfect for families and business travelers. Very quiet.'},
        {'name': 'The London West Hollywood', 'neighborhood': 'West Hollywood', 'lat': 34.0900, 'lng': -118.3800, 'address': '1020 N San Vicente Blvd, West Hollywood, CA 90069', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 84, 'notes': 'Modern luxury in West Hollywood. Great rooftop pool. Perfect for younger luxury travelers.'},
        {'name': 'The Andaz West Hollywood', 'neighborhood': 'West Hollywood', 'lat': 34.0920, 'lng': -118.3750, 'address': '8401 Sunset Blvd, West Hollywood, CA 90069', 'rate_low': 350, 'rate_mid': 550, 'rate_high': 850, 'quality': 81, 'notes': 'Hip hotel in West Hollywood. Great rooftop views. Perfect for younger travelers and creatives.'},
        {'name': 'The SLS Beverly Hills', 'neighborhood': 'Beverly Hills', 'lat': 34.0700, 'lng': -118.4000, 'address': '465 S La Cienega Blvd, Los Angeles, CA 90048', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 83, 'notes': 'Design-forward hotel in Beverly Hills. Very scene-y, great restaurants. Perfect for fashion and entertainment industry.'},
        {'name': 'The Palihouse West Hollywood', 'neighborhood': 'West Hollywood', 'lat': 34.0900, 'lng': -118.3800, 'address': '8465 Holloway Dr, West Hollywood, CA 90069', 'rate_low': 300, 'rate_mid': 500, 'rate_high': 800, 'quality': 79, 'notes': 'Boutique hotel in West Hollywood. Great value, scene-y. Perfect for younger travelers exploring WeHo.'},
        {'name': 'The Kimpton Everly Hotel', 'neighborhood': 'Hollywood', 'lat': 34.1000, 'lng': -118.3400, 'address': '1800 Argyle Ave, Los Angeles, CA 90028', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 75, 'notes': 'Modern hotel in Hollywood. Great rooftop pool. Perfect for younger travelers and creatives.'},
        {'name': 'The Freehand Los Angeles', 'neighborhood': 'Downtown LA', 'lat': 34.0440, 'lng': -118.2500, 'address': '416 W 8th St, Los Angeles, CA 90014', 'rate_low': 200, 'rate_mid': 350, 'rate_high': 550, 'quality': 72, 'notes': 'Hip hostel-hotel hybrid. Great for budget-conscious travelers and solo work trips. Very scene-y.'},
        {'name': 'The Nomad Los Angeles', 'neighborhood': 'Downtown LA', 'lat': 34.0500, 'lng': -118.2500, 'address': '649 S Olive St, Los Angeles, CA 90014', 'rate_low': 300, 'rate_mid': 500, 'rate_high': 800, 'quality': 80, 'notes': 'Beautiful hotel in downtown LA. Great restaurants and bars. Perfect for business travelers and creatives.'},
        {'name': 'The InterContinental Los Angeles', 'neighborhood': 'Downtown LA', 'lat': 34.0500, 'lng': -118.2550, 'address': '900 Wilshire Blvd, Los Angeles, CA 90017', 'rate_low': 350, 'rate_mid': 550, 'rate_high': 850, 'quality': 82, 'notes': 'Modern luxury in downtown LA. Great for business travelers. Excellent service and amenities.'},
    ],
    'SF': [
        {'name': 'The St. Regis San Francisco', 'neighborhood': 'SOMA', 'lat': 37.7850, 'lng': -122.4000, 'address': '125 3rd St, San Francisco, CA 94103', 'rate_low': 500, 'rate_mid': 700, 'rate_high': 1100, 'quality': 92, 'notes': 'Ultra-luxury in SOMA. Exceptional service, perfect for business travelers. Very quiet and discreet.'},
        {'name': 'The Four Seasons Hotel San Francisco', 'neighborhood': 'Financial District', 'lat': 37.7900, 'lng': -122.4050, 'address': '757 Market St, San Francisco, CA 94103', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 1000, 'quality': 91, 'notes': 'Classic Four Seasons luxury. Excellent service, perfect for families and business travelers.'},
        {'name': 'The Ritz-Carlton San Francisco', 'neighborhood': 'Nob Hill', 'lat': 37.7920, 'lng': -122.4100, 'address': '600 Stockton St, San Francisco, CA 94108', 'rate_low': 500, 'rate_mid': 700, 'rate_high': 1100, 'quality': 90, 'notes': 'Luxury on Nob Hill. Exceptional service, perfect for business travelers and families. Very quiet.'},
        {'name': 'The Proper Hotel San Francisco', 'neighborhood': 'Mid-Market', 'lat': 37.7750, 'lng': -122.4200, 'address': '1100 Market St, San Francisco, CA 94102', 'rate_low': 300, 'rate_mid': 500, 'rate_high': 800, 'quality': 83, 'notes': 'Hip hotel in Mid-Market. Great design, perfect for creatives and business travelers exploring SF.'},
        {'name': 'The Palace Hotel', 'neighborhood': 'Financial District', 'lat': 37.7880, 'lng': -122.4050, 'address': '2 New Montgomery St, San Francisco, CA 94105', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 87, 'notes': 'Historic luxury hotel. Beautiful architecture, excellent service. Perfect for business travelers.'},
        {'name': 'The Fairmont San Francisco', 'neighborhood': 'Nob Hill', 'lat': 37.7920, 'lng': -122.4100, 'address': '950 Mason St, San Francisco, CA 94108', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 86, 'notes': 'Iconic Nob Hill hotel. Historic charm, excellent service. Perfect for families and business travelers.'},
        {'name': 'The InterContinental San Francisco', 'neighborhood': 'SOMA', 'lat': 37.7850, 'lng': -122.4000, 'address': '888 Howard St, San Francisco, CA 94103', 'rate_low': 350, 'rate_mid': 550, 'rate_high': 850, 'quality': 84, 'notes': 'Modern luxury in SOMA. Great for business travelers. Excellent service and amenities.'},
        {'name': 'The Stanyan Park Hotel', 'neighborhood': 'Haight-Ashbury', 'lat': 37.7700, 'lng': -122.4500, 'address': '750 Stanyan St, San Francisco, CA 94117', 'rate_low': 200, 'rate_mid': 350, 'rate_high': 550, 'quality': 70, 'notes': 'Victorian charm in Haight-Ashbury. Great value, perfect for exploring the neighborhood.'},
        {'name': 'The Argonaut Hotel', 'neighborhood': 'Fisherman\'s Wharf', 'lat': 37.8080, 'lng': -122.4150, 'address': '495 Jefferson St, San Francisco, CA 94133', 'rate_low': 300, 'rate_mid': 500, 'rate_high': 800, 'quality': 78, 'notes': 'Boutique hotel in Fisherman\'s Wharf. Great location for tourists. Good value.'},
        {'name': 'The Hotel Vitale', 'neighborhood': 'Embarcadero', 'lat': 37.7950, 'lng': -122.3950, 'address': '8 Mission St, San Francisco, CA 94105', 'rate_low': 350, 'rate_mid': 550, 'rate_high': 850, 'quality': 81, 'notes': 'Modern hotel on Embarcadero. Great views, perfect for business travelers.'},
        {'name': 'The Marker San Francisco', 'neighborhood': 'Union Square', 'lat': 37.7880, 'lng': -122.4100, 'address': '501 Geary St, San Francisco, CA 94102', 'rate_low': 300, 'rate_mid': 500, 'rate_high': 800, 'quality': 79, 'notes': 'Boutique hotel in Union Square. Great location for shopping and business. Good value.'},
        {'name': 'The Clift Royal Sonesta', 'neighborhood': 'Union Square', 'lat': 37.7880, 'lng': -122.4100, 'address': '495 Geary St, San Francisco, CA 94102', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 76, 'notes': 'Historic hotel in Union Square. Great location, good value for business travelers.'},
        {'name': 'The Hotel Zetta San Francisco', 'neighborhood': 'SOMA', 'lat': 37.7850, 'lng': -122.4000, 'address': '55 5th St, San Francisco, CA 94103', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 75, 'notes': 'Hip hotel in SOMA. Great for younger travelers and creatives. Very scene-y.'},
        {'name': 'The Hotel Drisco', 'neighborhood': 'Pacific Heights', 'lat': 37.7900, 'lng': -122.4400, 'address': '2901 Pacific Ave, San Francisco, CA 94115', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 85, 'notes': 'Elegant boutique hotel in Pacific Heights. Very quiet, perfect for couples and business travelers.'},
        {'name': 'The Inn at the Presidio', 'neighborhood': 'Presidio', 'lat': 37.8000, 'lng': -122.4600, 'address': '42 Moraga Ave, San Francisco, CA 94129', 'rate_low': 350, 'rate_mid': 550, 'rate_high': 850, 'quality': 82, 'notes': 'Historic inn in Presidio. Very quiet and peaceful. Perfect for romantic getaways.'},
        {'name': 'The Taj Campton Place', 'neighborhood': 'Union Square', 'lat': 37.7880, 'lng': -122.4100, 'address': '340 Stockton St, San Francisco, CA 94108', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 1000, 'quality': 88, 'notes': 'Luxury in Union Square. Excellent service, perfect for business travelers and families.'},
        {'name': 'The Loews Regency San Francisco', 'neighborhood': 'Financial District', 'lat': 37.7900, 'lng': -122.4050, 'address': '222 Sansome St, San Francisco, CA 94104', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 85, 'notes': 'Modern luxury in Financial District. Great for business travelers. Excellent service.'},
        {'name': 'The Hotel Nikko San Francisco', 'neighborhood': 'Union Square', 'lat': 37.7880, 'lng': -122.4100, 'address': '222 Mason St, San Francisco, CA 94102', 'rate_low': 300, 'rate_mid': 500, 'rate_high': 800, 'quality': 80, 'notes': 'Modern hotel in Union Square. Great location, good value for business travelers.'},
        {'name': 'The Hotel Zeppelin San Francisco', 'neighborhood': 'Union Square', 'lat': 37.7880, 'lng': -122.4100, 'address': '545 Post St, San Francisco, CA 94102', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 74, 'notes': 'Hip hotel in Union Square. Great for younger travelers and creatives. Very scene-y.'},
        {'name': 'The Orchard Garden Hotel', 'neighborhood': 'Union Square', 'lat': 37.7880, 'lng': -122.4100, 'address': '466 Bush St, San Francisco, CA 94108', 'rate_low': 300, 'rate_mid': 500, 'rate_high': 800, 'quality': 77, 'notes': 'Eco-friendly hotel in Union Square. Great value, perfect for business travelers.'},
        {'name': 'The Hotel Triton', 'neighborhood': 'Union Square', 'lat': 37.7880, 'lng': -122.4100, 'address': '342 Grant Ave, San Francisco, CA 94108', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 73, 'notes': 'Boutique hotel in Union Square. Great location, good value for younger travelers.'},
        {'name': 'The Galleria Park Hotel', 'neighborhood': 'Financial District', 'lat': 37.7900, 'lng': -122.4050, 'address': '191 Sutter St, San Francisco, CA 94104', 'rate_low': 300, 'rate_mid': 500, 'rate_high': 800, 'quality': 76, 'notes': 'Boutique hotel in Financial District. Great for business travelers. Good value.'},
        {'name': 'The Hotel G San Francisco', 'neighborhood': 'Union Square', 'lat': 37.7880, 'lng': -122.4100, 'address': '386 Geary St, San Francisco, CA 94102', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 72, 'notes': 'Modern hotel in Union Square. Great for younger travelers and creatives. Good value.'},
        {'name': 'The Hotel des Arts', 'neighborhood': 'Union Square', 'lat': 37.7880, 'lng': -122.4100, 'address': '447 Bush St, San Francisco, CA 94108', 'rate_low': 200, 'rate_mid': 350, 'rate_high': 550, 'quality': 68, 'notes': 'Art-focused hotel in Union Square. Great value, perfect for budget-conscious travelers.'},
        {'name': 'The Hotel Carlton', 'neighborhood': 'Nob Hill', 'lat': 37.7920, 'lng': -122.4100, 'address': '1075 Sutter St, San Francisco, CA 94109', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 71, 'notes': 'Boutique hotel in Nob Hill. Great location, good value for business travelers.'},
    ],
    'London': [
        {'name': 'The Savoy', 'neighborhood': 'Covent Garden', 'lat': 51.5100, 'lng': -0.1200, 'address': 'Strand, London WC2R 0EU, UK', 'rate_low': 500, 'rate_mid': 750, 'rate_high': 1200, 'quality': 95, 'notes': 'Iconic London landmark. Ultra-luxury with exceptional service. Perfect for high-profile guests and special occasions.'},
        {'name': 'Claridge\'s', 'neighborhood': 'Mayfair', 'lat': 51.5120, 'lng': -0.1470, 'address': 'Brook St, London W1K 4HR, UK', 'rate_low': 600, 'rate_mid': 850, 'rate_high': 1300, 'quality': 96, 'notes': 'Ultra-luxury in Mayfair. Exceptional service, very quiet and discreet. Perfect for high-profile guests.'},
        {'name': 'The Connaught', 'neighborhood': 'Mayfair', 'lat': 51.5120, 'lng': -0.1480, 'address': 'Carlos Pl, London W1K 2AL, UK', 'rate_low': 600, 'rate_mid': 850, 'rate_high': 1300, 'quality': 95, 'notes': 'Ultra-luxury in Mayfair. Exceptional service, perfect for business travelers and families. Very quiet.'},
        {'name': 'The Ritz London', 'neighborhood': 'Mayfair', 'lat': 51.5070, 'lng': -0.1470, 'address': '150 Piccadilly, London W1J 9BR, UK', 'rate_low': 550, 'rate_mid': 800, 'rate_high': 1300, 'quality': 94, 'notes': 'Iconic luxury in Mayfair. Exceptional service, perfect for high-profile guests and special occasions.'},
        {'name': 'The Berkeley', 'neighborhood': 'Knightsbridge', 'lat': 51.5000, 'lng': -0.1600, 'address': 'Wilton Pl, London SW1X 7RL, UK', 'rate_low': 500, 'rate_mid': 750, 'rate_high': 1200, 'quality': 93, 'notes': 'Ultra-luxury in Knightsbridge. Exceptional service, perfect for families and business travelers.'},
        {'name': 'The Edition London', 'neighborhood': 'Fitzrovia', 'lat': 51.5200, 'lng': -0.1400, 'address': '10 Berners St, London W1T 3NP, UK', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 87, 'notes': 'Ian Schrager design hotel. Very scene-y with great restaurants and bars. Perfect for younger luxury travelers.'},
        {'name': 'The Ned', 'neighborhood': 'City of London', 'lat': 51.5150, 'lng': -0.0900, 'address': '27 Poultry, London EC2R 8AJ, UK', 'rate_low': 350, 'rate_mid': 550, 'rate_high': 850, 'quality': 85, 'notes': 'Hip hotel in the City. Great restaurants and bars. Perfect for business travelers and creatives.'},
        {'name': 'The Hoxton Shoreditch', 'neighborhood': 'Shoreditch', 'lat': 51.5250, 'lng': -0.0800, 'address': '81 Great Eastern St, London EC2A 3HU, UK', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 78, 'notes': 'Hip hotel in Shoreditch. Great for younger travelers and creatives. Very scene-y, startup-friendly.'},
        {'name': 'The Chiltern Firehouse', 'neighborhood': 'Marylebone', 'lat': 51.5200, 'lng': -0.1500, 'address': '1 Chiltern St, London W1U 7PA, UK', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 1000, 'quality': 88, 'notes': 'Very scene-y hotel with incredible restaurant. Attracts fashion and entertainment industry. Can be loud.'},
        {'name': 'The Ham Yard Hotel', 'neighborhood': 'Soho', 'lat': 51.5120, 'lng': -0.1350, 'address': '1 Ham Yard, London W1D 7DT, UK', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 86, 'notes': 'Firmdale Hotels property with stunning design. Very quiet and elegant. Perfect for business travelers.'},
        {'name': 'The Soho Hotel', 'neighborhood': 'Soho', 'lat': 51.5120, 'lng': -0.1350, 'address': '4 Richmond Mews, London W1D 3DH, UK', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 87, 'notes': 'Firmdale Hotels property with Kit Kemp design. Very quiet and elegant. Perfect Soho location.'},
        {'name': 'The Covent Garden Hotel', 'neighborhood': 'Covent Garden', 'lat': 51.5100, 'lng': -0.1200, 'address': '10 Monmouth St, London WC2H 9HB, UK', 'rate_low': 400, 'rate_mid': 600, 'rate_high': 950, 'quality': 86, 'notes': 'Firmdale Hotels property with beautiful design. Very quiet and elegant. Perfect for theater lovers.'},
        {'name': 'The Rosewood London', 'neighborhood': 'Holborn', 'lat': 51.5150, 'lng': -0.1200, 'address': '252 High Holborn, London WC1V 7EN, UK', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 1000, 'quality': 89, 'notes': 'Luxury in Holborn. Excellent service, perfect for business travelers. Very quiet and discreet.'},
        {'name': 'The Langham London', 'neighborhood': 'Marylebone', 'lat': 51.5150, 'lng': -0.1470, 'address': '1C Portland Pl, London W1B 1JA, UK', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 1000, 'quality': 90, 'notes': 'Classic luxury in Marylebone. Excellent service, perfect for families and business travelers.'},
        {'name': 'The Four Seasons Hotel London', 'neighborhood': 'Mayfair', 'lat': 51.5120, 'lng': -0.1480, 'address': 'Hamilton Pl, London W1J 7DR, UK', 'rate_low': 500, 'rate_mid': 750, 'rate_high': 1200, 'quality': 92, 'notes': 'Ultra-luxury Four Seasons. Exceptional service, perfect for families and high-profile guests.'},
        {'name': 'The Ritz-Carlton London', 'neighborhood': 'Piccadilly', 'lat': 51.5070, 'lng': -0.1470, 'address': '150 Piccadilly, London W1J 9BR, UK', 'rate_low': 500, 'rate_mid': 750, 'rate_high': 1200, 'quality': 91, 'notes': 'Classic luxury in Piccadilly. Exceptional service, perfect for business travelers and families.'},
        {'name': 'The Goring', 'neighborhood': 'Belgravia', 'lat': 51.4950, 'lng': -0.1500, 'address': '15 Beeston Pl, London SW1W 0JW, UK', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 1000, 'quality': 88, 'notes': 'Family-owned luxury in Belgravia. Exceptional service, very quiet and discreet. Perfect for special occasions.'},
        {'name': 'The Lanesborough', 'neighborhood': 'Belgravia', 'lat': 51.4950, 'lng': -0.1500, 'address': 'Hyde Park Corner, London SW1X 7TA, UK', 'rate_low': 550, 'rate_mid': 800, 'rate_high': 1300, 'quality': 93, 'notes': 'Ultra-luxury in Belgravia. Exceptional service, perfect for high-profile guests. Very quiet and discreet.'},
        {'name': 'The Bulgari Hotel London', 'neighborhood': 'Knightsbridge', 'lat': 51.5000, 'lng': -0.1600, 'address': '171 Knightsbridge, London SW7 1DW, UK', 'rate_low': 600, 'rate_mid': 850, 'rate_high': 1300, 'quality': 94, 'notes': 'Ultra-luxury in Knightsbridge. Exceptional service, perfect for high-profile guests. Very scene-y but private.'},
        {'name': 'The Corinthia London', 'neighborhood': 'Westminster', 'lat': 51.5070, 'lng': -0.1250, 'address': 'Whitehall Pl, London SW1A 2BD, UK', 'rate_low': 450, 'rate_mid': 650, 'rate_high': 1000, 'quality': 89, 'notes': 'Luxury in Westminster. Excellent service, perfect for business travelers. Very quiet and professional.'},
        {'name': 'The Mondrian London', 'neighborhood': 'South Bank', 'lat': 51.5050, 'lng': -0.1150, 'address': '20 Upper Ground, London SE1 9PD, UK', 'rate_low': 350, 'rate_mid': 550, 'rate_high': 850, 'quality': 82, 'notes': 'Modern luxury on South Bank. Great views, perfect for business travelers and creatives.'},
        {'name': 'The Shoreditch House', 'neighborhood': 'Shoreditch', 'lat': 51.5250, 'lng': -0.0800, 'address': 'Ebor St, London E1 6AW, UK', 'rate_low': 300, 'rate_mid': 500, 'rate_high': 800, 'quality': 80, 'notes': 'Members club hotel in Shoreditch. Very scene-y, perfect for creatives and startups. Can be loud.'},
        {'name': 'The Ace Hotel London', 'neighborhood': 'Shoreditch', 'lat': 51.5250, 'lng': -0.0800, 'address': '100 Shoreditch High St, London E1 6JQ, UK', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 76, 'notes': 'Hip hotel in Shoreditch. Great for younger travelers and creatives. Very startup-friendly.'},
        {'name': 'The Hoxton Holborn', 'neighborhood': 'Holborn', 'lat': 51.5150, 'lng': -0.1200, 'address': '199-206 High Holborn, London WC1V 7BD, UK', 'rate_low': 250, 'rate_mid': 400, 'rate_high': 650, 'quality': 77, 'notes': 'Hip hotel in Holborn. Great for business travelers and creatives. Good value, scene-y lobby.'},
        {'name': 'The Zetter Townhouse Clerkenwell', 'neighborhood': 'Clerkenwell', 'lat': 51.5250, 'lng': -0.1100, 'address': '49-50 St John\'s Square, London EC1V 4JJ, UK', 'rate_low': 300, 'rate_mid': 500, 'rate_high': 800, 'quality': 79, 'notes': 'Boutique hotel in Clerkenwell. Great for business travelers and creatives. Good value.'},
    ]
}

def generate_sql():
    """Generate SQL INSERT statements for all hotels"""
    sql_parts = []
    sql_parts.append("-- ============================================================================")
    sql_parts.append("-- Seed Data: Top 25 Hotels in NYC, LA, SF, and London")
    sql_parts.append("-- Total: 100 hotels for testing and development")
    sql_parts.append("-- ============================================================================")
    sql_parts.append("")
    
    for city, hotels in hotels_data.items():
        sql_parts.append(f"-- {city} Hotels ({len(hotels)})")
        sql_parts.append("INSERT INTO hotels (name, brand_group, address, lat, lng, neighborhood, primary_city, website_url, pier_booking_link, booking_partners, star_rating, room_count, opening_year, last_renovated_year, rate_low, rate_mid, rate_high, check_in_time, check_out_time, loyalty_programs, business_cluster_proximity, walkability_score_internal, transit_access, airport_distance_minutes, near_key_areas, design_style, room_style, bathroom_quality, instagram_worthy, atmosphere, guest_mix, noise_level, scene_level, service_style, staff_kindness_score, checkin_flexibility_score, late_checkout_friendliness, discretion_score, concierge_quality, problem_resolution, gym_quality, spa_quality, pool_type, food_drink_quality, bar_scene, coworking_space, meeting_rooms, pet_friendly, wifi_quality, desk_in_room, power_outlets, creator_friendly, startup_friendly, good_for_solo_work, good_for_couples, good_for_families, good_for_long_stays, good_for_offsites, good_for_board_meetings, pier_perk_level, pier_benefits, quality_score_internal, notes_curated, is_active, is_experimental) VALUES")
        
        values = []
        for i, hotel in enumerate(hotels):
            # Determine attributes based on quality score and city
            quality = hotel['quality']
            is_luxury = quality >= 88
            is_scene = quality >= 75 and quality < 88 and city in ['NYC', 'LA', 'London']
            
            # Set defaults based on quality
            star_rating = 4.5 if quality >= 85 else 4.0
            if quality >= 95:
                star_rating = 5.0
            elif quality < 75:
                star_rating = 3.5
            
            service_style = 'ultra-attentive' if is_luxury else 'chill' if is_scene else 'discreet'  # Valid enum values: 'ultra-attentive', 'discreet', 'chill', 'inconsistent'
            staff_kindness = 9 if is_luxury else 7 if is_scene else 8
            noise_level = 2 if is_luxury else 4 if is_scene else 3
            scene_level = 2 if is_luxury else 4 if is_scene else 3
            
            # Fix constraint violations: concierge_quality must be 0..3 (not 4)
            concierge_quality = 2  # Changed from 4 to 2 to satisfy CHECK constraint (0..3)
            
            # Generate realistic values - escape apostrophes for SQL
            name_escaped = hotel['name'].replace("'", "''")
            notes_escaped = hotel['notes'].replace("'", "''")
            neighborhood_escaped = hotel['neighborhood'].replace("'", "''")
            address_escaped = hotel['address'].replace("'", "''")
            
            # Determine good_for_board_meetings based on quality and city
            good_for_board_meetings = is_luxury  # Luxury hotels are better for board meetings
            
            # Build value with explicit enum casts matching the schema
            # Column order matches schema: name, brand_group, address, lat, lng, neighborhood, primary_city, website_url, pier_booking_link, booking_partners, star_rating, room_count, opening_year, last_renovated_year, rate_low, rate_mid, rate_high, check_in_time, check_out_time, loyalty_programs, business_cluster_proximity, walkability_score_internal, transit_access, airport_distance_minutes, near_key_areas, design_style, room_style, bathroom_quality, instagram_worthy, atmosphere, guest_mix, noise_level, scene_level, service_style, staff_kindness_score, checkin_flexibility_score, late_checkout_friendliness, discretion_score, concierge_quality, problem_resolution, gym_quality, spa_quality, pool_type, food_drink_quality, bar_scene, coworking_space, meeting_rooms, pet_friendly, wifi_quality, desk_in_room, power_outlets, creator_friendly, startup_friendly, good_for_solo_work, good_for_couples, good_for_families, good_for_long_stays, good_for_offsites, good_for_board_meetings, pier_perk_level, pier_benefits, quality_score_internal, notes_curated, is_active, is_experimental
            value = f"('{name_escaped}', 'Independent', '{address_escaped}', {hotel['lat']}, {hotel['lng']}, '{neighborhood_escaped}', '{city}'::public.primary_city_enum, 'https://example.com', NULL, '[\"Amex FHR\", \"Virtuoso\"]'::jsonb, {star_rating}, {150 + (i % 100)}, {2000 + (i % 20)}, {2015 + (i % 8)}, {hotel['rate_low']}, {hotel['rate_mid']}, {hotel['rate_high']}, '15:00'::time, '12:00'::time, ARRAY[]::text[], ARRAY['{neighborhood_escaped}']::text[], 5, 'excellent'::public.transit_access_enum, {30 + (i % 30)}, ARRAY['{neighborhood_escaped}']::text[], ARRAY['minimalist', 'art-driven']::text[], ARRAY['spacious']::text[], 'luxury'::public.bathroom_quality_enum, true, ARRAY['quiet', 'business']::text[], ARRAY['founders/VC', 'finance']::text[], {noise_level}, {scene_level}, '{service_style}'::public.service_style_enum, {staff_kindness}, 4, 4, 4, {concierge_quality}, 'excellent'::public.problem_resolution_enum, 2, 2, 'none'::public.pool_type_enum, 'destination restaurant'::public.food_drink_quality_enum, 'quiet cocktails'::public.bar_scene_enum, false, true, true, 5, true, 'abundant'::public.power_outlets_enum, true, false, true, true, false, true, true, {str(good_for_board_meetings).lower()}, 'VIP partner'::public.pier_perk_level_enum, ARRAY['late checkout', 'breakfast']::text[], {hotel['quality']}, '{notes_escaped}', true, false)"
            values.append(value)
        
        sql_parts.append(",\n".join(values) + ";")
        sql_parts.append("")
    
    return "\n".join(sql_parts)

if __name__ == '__main__':
    sql = generate_sql()
    with open('seed_top_hotels_complete.sql', 'w') as f:
        f.write(sql)
    print(f"Generated SQL file with {sum(len(hotels) for hotels in hotels_data.values())} hotels")

